var should = require('should'); //for mocha tests
var parse = require('../lib/handlerParser.js').parse;
var fs = require('fs');
var _ = require('lodash');

var dir = __dirname + '/fixtures';

describe("handlerParser.parse method", function() {
    it("generated by cli", function(done) {

        parse(dir + '/handlerParser', function(err, paths) {
            if (err) return done(err);
            
            var compareWith = {
                url: '/books',
                method: 'get',
                action: 'list',
                handlerPath: '/home/petea/vatican/test/fixtures/handlerParser/default.js',
                handlerName: 'default',
            };
            _.isEqual(paths[0], compareWith).should.be.true;
            done();
        });
    });
});
