var should = require('should'); //for mocha tests
var parse = require('../lib/handlerParser.js').parse;
var fs = require('fs');
var _ = require('lodash');

var dir = __dirname + '/fixtures/handlerParser';

describe("handlerParser.parse method", function() {
    describe('', function() { 
        it("the @endpoint does not follow any character", function(done) {
            var dirname = dir + '/notFollowAnyCharacter';
            parse(dirname, function(err, paths) {
                if (err) return done(err);

                paths.length.should.be.equal(0);
                done();
            });
        });
    });

    it("independent of number of spaces and tabs between the elements", function(done) {
        var dirname = dir + '/independentSpacesTabs';

        parse(dirname, function(err, paths) {
            if (err) return done(err);

            paths.length.not.equal(0);
            
            var compareWith = {
                url: '/books',
                method: 'get',
                action: 'list',
                handlerPath: dirname + '/default.js',
                handlerName: 'default',
                name: 'name_param',
            };

            paths[0].url.should.be.equal(compareWith.url);
            paths[0].method.should.be.equal(compareWith.method);
            paths[0].action.should.be.equal(compareWith.action);
            paths[0].handlerPath.should.be.equal(compareWith.handlerPath);
            paths[0].handlerName.should.be.equal(compareWith.handlerName);
            paths[0].name.should.be.equal(compareWith.name);

            _.isEqual(paths[0], compareWith).should.be.true;
            done();
        });
    });


    it("independent of comments", function(done) {
        var dirname = dir + '/independentComments';

        parse(dirname, function(err, paths) {
            if (err) return done(err);
            
            paths.length.not.equal(0);

            var compareWith = {
                url: '/books',
                method: 'get',
                action: 'list',
                handlerPath: dirname + '/default.js',
                handlerName: 'default',
                name: 'name_param',
            };

            paths[0].url.should.be.equal(compareWith.url);
            paths[0].method.should.be.equal(compareWith.method);
            paths[0].action.should.be.equal(compareWith.action);
            paths[0].handlerPath.should.be.equal(compareWith.handlerPath);
            paths[0].handlerName.should.be.equal(compareWith.handlerName);
            paths[0].name.should.be.equal(compareWith.name);

            _.isEqual(paths[0], compareWith).should.be.true;
            done();
        });
    });

    it("independent of number of new lines between @endpoint and function declaration", function(done) {
        var dirname = dir + '/independentSpacesTabs';

        parse(dirname, function(err, paths) {
            if (err) return done(err);
            
            paths.length.not.equal(0);

            var compareWith = {
                url: '/books',
                method: 'get',
                action: 'list',
                handlerPath: dirname + '/default.js',
                handlerName: 'default',
                name: 'name_param',
            };

            paths[0].url.should.be.equal(compareWith.url);
            paths[0].method.should.be.equal(compareWith.method);
            paths[0].action.should.be.equal(compareWith.action);
            paths[0].handlerPath.should.be.equal(compareWith.handlerPath);
            paths[0].handlerName.should.be.equal(compareWith.handlerName);
            paths[0].name.should.be.equal(compareWith.name);

            _.isEqual(paths[0], compareWith).should.be.true;
            done();
        });
    });

    describe("generated by cli", function() {
        it("without name param" ,function(done) {

            var dirname = dir + '/withoutNameParam';
            parse(dirname, function(err, paths) {
                if (err) return done(err);
                
                var compareWith = {
                    url: '/books',
                    method: 'get',
                    action: 'list',
                    handlerPath: dirname + '/default.js',
                    handlerName: 'default',
                };

                paths[0].url.should.be.equal(compareWith.url);
                paths[0].method.should.be.equal(compareWith.method);
                paths[0].action.should.be.equal(compareWith.action);
                paths[0].handlerPath.should.be.equal(compareWith.handlerPath);
                paths[0].handlerName.should.be.equal(compareWith.handlerName);

                _.isEqual(paths[0], compareWith).should.be.true;
                done();
            });
        });

        it("with name param" ,function(done) {

            var dirname = dir + '/withNameParam';
            parse(dirname, function(err, paths) {
                if (err) return done(err);
                
                var compareWith = {
                    url: '/books',
                    method: 'get',
                    action: 'list',
                    name: 'name_param',
                    handlerPath: dirname + '/default.js',
                    handlerName: 'default',
                };

                paths[0].url.should.be.equal(compareWith.url);
                paths[0].method.should.be.equal(compareWith.method);
                paths[0].action.should.be.equal(compareWith.action);
                paths[0].handlerPath.should.be.equal(compareWith.handlerPath);
                paths[0].handlerName.should.be.equal(compareWith.handlerName);
                paths[0].name.should.be.equal(compareWith.name);

                _.isEqual(paths[0], compareWith).should.be.true;
                done();
            });
        });
    });

});
